### ISSUE TITLE
TextLayout objects should avoid using `Vec` internally

### ISSUE THREAD

**Issue by cmyr** [linebender/piet#296]
we would like layouts to be relatively cheap to clone; we don't need to mutate them, so they should be able to store vec-like data as `Rc<[T]>`.

**Comment by raphlinus** [comment]
I'm unsure about this. For one, we *can* mutate it, by setting the width. For two, I don't want to preclude sending them across threads, because it makes sense for background threads to create them. And for three, if there are clones around, it might complicate safety invariants with the platform.

Another possibility is for the client to hold the text layout in its own refcount container. But that would work quite a bit better if the layouts were actually immutable. We considered updating the width as an immutable operation, which would make sense if the struct was Rust-only, but likely not as efficient on other platforms, which is why it's `&mut`.

Something else that's occurring to me is allowing (but not requiring) copy-on-write semantics, perhaps leveraging `get_mut` or similar to optimize in the single-owner case. But that's only an optimization if the client is not keeping lots of clones.

**Comment by cmyr** [comment]
Addressing some of your points, not quite in order:

- this type already implements `Clone`, it just currently does it inefficiently. This is necessary in druid, for things like `paint_with_z_level`, since we need to store a closure on the heap that will do the drawing; if this closure draws text, we need to store that text on the heap.

- I was unclear about mutability: what i man is that we rebuild all these vecs when we set width, we don't mutate them in place, so we don't need a collection type that is mutable, i.e. we can use a boxed/rc'd/arc'd slice.

- our current position on thread-safety is that we aren't sure, and these types are not currently `Send` or `Sync`.
