### ISSUE TITLE
0.2.0-pre6 broke crochet

### ISSUE THREAD

**Issue by Fi3** [linebender/piet#347]
This [commit](https://github.com/linebender/piet/commit/1d70107647b11c011e99822b792a40ae2a1894f8#diff-4da1cafb54a298d41de4bb0ce947085c957ce37a839beea02d6aa072bd2a192b) broke this [version of druid](https://github.com/linebender/druid/tree/7a3251b9b89df11af653189f2be04c7304861acf) that is used in crochet because two different version of kurbo are required 0.6.3 and 0.7.0.

**Comment by cmyr** [comment]
I would suggest patching cargo.toml to use kurbo 0.7.0

**Comment by raphlinus** [comment]
I don't think that will work. Currently, crochet needs to be pinned on an old version of druid because of https://github.com/linebender/druid/issues/1258. That in turn needs to pin piet 0.2.0-pre4 because of the various changes.

I think the short-term patch might be to commit Cargo.lock on crochet. The longer term solution is to fix the druid dynamic issues so we can move the pin forward on crochet.

**Comment by cmyr** [comment]
Closing as we've got at least a temporary fix in place.
