### ISSUE TITLE
No easy way to get the whitespace-inclusive width of a text layout

### ISSUE THREAD

**Issue by cmyr** [linebender/piet#357]
This has come up in druid, and is a thing that we really should provide. There are various ways to go about it, with the easiest being some method on `TextLayout` like `width_including_whitespace()`. It's also arguable that we should provide a `whitespace_width` field on `LineMetric`, although this may be slightly annoying to implement on windows.

**Comment by raphlinus** [comment]
Not surprised to see that we do need widths both inclusive and exclusive of whitespace.

I haven't dug into the code, but am not sure what the problem is on Windows; the [DWRITE_TEXT_METRICS](https://docs.microsoft.com/en-us/windows/win32/api/dwrite/ns-dwrite-dwrite_text_metrics) structure (return from `TextLayout::GetMetrics`) has both `width` and `widthIncludingTrailingWhitespace`, for this reason. But it's possible I'm missing something.

**Comment by cmyr** [comment]
DWrite makes it easy for us to get the whitespace width of the full layout, but difficult to get it for each visual line, and CoreText is the inverse. 🤷

**Comment by raphlinus** [comment]
Ah, right. I think we're going to have to do a DWrite run iterator. I have a working prototype of that in my local branch (done with hand-rolled com vtables), and can dust that off as needed.

**Comment by cmyr** [comment]
I think we can punt on that for now, but only supporting whitespace width for the full layout, this will cover our main need (which is correct h-scroll in a text layout with trailing whitespace)
