### ISSUE TITLE
Rendering on a window

### ISSUE THREAD

**Issue by calebwin** [linebender/piet#45]
I am very new to graphics rendering and stuff so this is probably a very uninformed question. But, could someone kindly point me towards how I can use Piet to actually render graphics on a screen?

What kind of other pieces to I need to put together along with Piet to get a rectangle or something on a window?

**Comment by calebwin** [comment]
Just to clarify - Piet lets me use a single API that can use different back-ends to take my imperative commands to render 2D graphics and generate a bitmap. I can then render this bitmap using something else.

Am I understanding this correctly?

**Comment by raphlinus** [comment]
Right now, [druid-shell](https://github.com/xi-editor/druid/tree/master/druid-shell) is the best supported way to get rendering in a window. Otherwise, it's possible to use your own methods to open a window and get a context that can be handed off to a piet back-end, but all this is currently very bare-bones.

**Comment by calebwin** [comment]
Got it. And `druid-shell` currently only supports Windows - correct?

**Comment by raphlinus** [comment]
Some support for macOS as well, and there are experimental branches for Linux/GTK and web. We'll get there :)

**Comment by calebwin** [comment]
Cool! Thanks.
