### ISSUE TITLE
Clarifying project status

### ISSUE THREAD

**Issue by elliottslaughter** [linebender/piet#541]
I see the note at https://github.com/linebender/piet#piet-is-in-maintenance-mode . I am fine with the project being stable, but even a stable project needs to be maintained. Is piet getting this maintenance? I realize you can't predict the future, but I'm mostly hoping to get a sense of the pulse of the project in terms of who is around to fix things that break, especially as the underlying platforms evolve.

Thanks and sorry if this has been asked before.

**Comment by xStrom** [comment]
The underlying platforms are unlikely to change in a way that impacts Piet in the next few years. So this is really a question of the far future and basically impossible to say. It's an open source project by volunteers, so no guarantees.

Otherwise, like the note says Piet is in maintenance mode. Bug fixes will get reviewed and merged eventually. Mere reports might not result in code though, because our time is limited and we're involved with a lot of projects.

**Comment by elliottslaughter** [comment]
Thanks!
