### ISSUE TITLE
Gradient::new concept

### ISSUE THREAD

**Issue by futurepaul** [linebender/piet#72]
Now that I've created a few gradients, I believe it would be possible to make them slightly nicer to use with a constructor.

My thinking is something like this:
```rust
Gradient::new_linear(shape: impl Shape, stops: Vec<GradientStop>, rotation: f64)

Gradient::new_radial(shape: impl Shape, stops: Vec<GradientStop>)
```

For linear you could use the top and bottom of the shape's bounding_box for start and end points if rotation is 0. Not sure how to calculate it otherwise, **so maybe this won't actually work**. But it would be nice! :)

This gives you all the expressivity of CSS afaik while saving the user from needing to calculate the specific positions for the start and end points.

If it can't be done without having to define explicit start and end points (the main convenience I'm hoping to gain) then it might not be worth the hassle.

**Comment by raphlinus** [comment]
Thanks for the suggestion, we'll try to figure out how to make it work.

I'll note that a "gradient" resource, especially in the Direct2D sense, has the geometry baked on. So a constructor like this would not be able to create an object that's a thin wrapper around, for example [LinearGradientBrush](https://docs.microsoft.com/en-us/windows/win32/api/d2d1/nn-d2d1-id2d1lineargradientbrush).

But I can think of other possible approaches. We could think of a "gradient recipe" object that waits until it comes in contact with a bounding box before being turned into a Direct2D brush object. This could could all be wired up so it's a valid input the piet `Brush` type, or we could have new methods.

I'll also point to SwiftUI, which uses the concept of [UnitPoint](https://developer.apple.com/documentation/swiftui/unitpoint) in the [LinearGradient](https://developer.apple.com/documentation/swiftui/lineargradient) constructor. That allows values such as `.top`, which all seem to be computed based on the object bbox.

**Comment by cmyr** [comment]
Ah I haven't really touched gradients much, so the news that stops are in absolute coordinates is new to me.

This is interesting, though, because maybe it really gives us the opportunity to get rid of the 'brush' abstraction?

My thinking is along the lines of the "gradient recipe" raph mentions: gradient stops should be normalized in the space `0.0..=1.0` (possibly `0..2π` if we want radial stops in radians, I'm not sure if this is a convention), and should only be turned into a concrete gradient when used with a specific shape. This would let a 'gradient' be reused across any number of shapes.

If we did this, I think it would then make sense to use `Color` and `Gradient` directly, and let 'brush creation' be a backend concern, where the backend can cache instances of brushes when and where it makes sense.

I think this would be no worse than now in the general case, since so far we have tended to just create brushes as needed in the `paint` method, so it seems irrelevant whether that happens in client code or in druid itself.
